version: '3.6'
services:

  template_postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"

  template_api:
    container_name: template_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - template_postgres
